### ISSUE TITLE
Manually deleting check gives API error

### ISSUE THREAD

**Issue by bitfield** [checkly/terraform-provider-checkly#11]
Migrated from https://github.com/bitfield/terraform-provider-checkly/issues/9

Steps to reproduce:

Create check via terraform
Delete check via UI
run terraform apply or terraform plan

Result:

checkly_check.example-check: Refreshing state... [id=36152cfc-f65c-42a9-b922-7eadd23c5840]

Error: API error: unexpected response status 404: "{\"statusCode\":404,\"error\":\"Not Found\"}"

Confirmed this still happens on v0.6.0

**Comment by tnolet** [comment]
I tested the proposed fix and the behaviour is not as expected:

plugin version: 0.6.4-rc1
terraform: 0.12.29

```tf
variable "checkly_api_key" {
}

provider "checkly" {
  api_key = var.checkly_api_key
}

resource "checkly_check" "api-check-1" {
  name              = "API check 1"
  type              = "API"
  frequency         = 60
  activated         = true
  muted             = true
  double_check      = true
  max_response_time = 18000
  locations = [
    "eu-central-1",
    "us-east-2",
  ]

  request {
    method = "GET"
    url    = "https://api.checklyhq.com/public-stats"

    assertion {
      comparison = "EQUALS"
      property   = ""
      source     = "STATUS_CODE"
      target     = "200"
    }
  }

  use_global_alert_settings = true
}
```

1. Run `terraform apply`.  This creates the check as expected
2. Delete the check in the Checkly UI.
3. Run `terraform plan`. I would expected Terraform to tell me that a resource is missing and it will be created.
4. What happens is that the check is already created, even when not running `terraform apply`
5. This also happens with `terraform refresh`

Both `terraform refresh` and `terraform plan` should not modify anything.

**Comment by tnolet** [comment]
@kjda any update on this one?

**Comment by tnolet** [comment]
@kjda I tested v0.6.4-rc.2 and this bug seems fixed! Let's keep it open till we roll out the fix and then close manually

**Comment by kjda** [comment]
@tnolet ok, will roll it out today! but tickets get auto closed when we merge fix into master

**Comment by kjda** [comment]
rolled out in v0.6.4
