### ISSUE TITLE
Looks like existing releases changed checksums

### ISSUE THREAD

**Issue by gkranis** [checkly/terraform-provider-checkly#118]
Looks like existing releases changed checksums, at least `0.6.9`. That version has recently been re-released in github. Just wanted to verify that no malicious stuff is happening before we regenerate our  `.terraform.lock.hcl`.

A host without a cached provider in `./.terraform` fails
![image](https://user-images.githubusercontent.com/4227126/154489900-94486849-0156-46ec-9bfc-1b10eebb9912.png)

Here's the checksum of the provider binary on a host where the provider is already in `./.terraform` (so old donwload)
![image](https://user-images.githubusercontent.com/4227126/154491196-dc199f6f-2852-4648-a9b0-88d4c8890ffa.png)

And here's the checksum of the same binary freshly downloaded from Github releases
![image](https://user-images.githubusercontent.com/4227126/154491700-d459a724-d02f-4e2b-a0a0-bec5e4706d20.png)

Note that re-releasing same versions breaks trust on first use mentioned here https://www.terraform.io/language/files/dependency-lock#checksum-verification

**Comment by ianaya89** [comment]
Hi @gkranis thanks for your concern. 
Nothing malicious happened, but something really stupid did. I accidentally deleted this repo and we lost all the releases. 
I am trying to work with Terraform Support in order to fix that, but is getting some time. I also made new path releases for all of our versions:

```
v0.8.3
v1.0.1
v1.1.1
v1.2.2
v1.3.1
v1.4.1 
``` 

Please let me know if that works for you or have more questions.

**Comment by gkranis** [comment]
thanks, no questions then :)

**Comment by gkranis** [comment]
I thought the issue was that my lockfile had the old hashes

I tried to regenerate my lockfile and it still fails
![image](https://user-images.githubusercontent.com/4227126/156797764-247d4f7c-0594-4e4c-8cd3-0a01035b1a0c.png)

From that im getting that provider version 0.6.9 on the registry is at an inconsistent  state

**Comment by ianaya89** [comment]
@gkranis can you tri with version `v0.8.3`? That version was recently generated and should have the correct checksums.

I will also recommend migrating to the latest version (v1.4.1)  so you can benefit from all of our latest features. Will happy to assist you if is needed. Don't hesitate to reach me if needed ( nacho[at]checklyhq.com )

**Comment by gkranis** [comment]
thanks we will update to a newer version then
