### ISSUE TITLE
basic_auth should not be a required field

### ISSUE THREAD

**Issue by dijitali** [checkly/terraform-provider-checkly#14]
Just trying out the latest release to use the new group functionality and have found my Checkly Terraform configuration is not immediately compatible.  I came here to look at the examples to see if there were wider changes but unfortunately they are no longer valid (from the validation error I think the only issue is that `basic_auth` is now a required field).

It looks like there's on-going work in #7 to make this provider official, at which point we'll be able to see docs on the Terraform Registry: https://registry.terraform.io/browse/providers.

In the interim, is it possible to update the examples in the readme or perhaps even add some examples that get run and integration tested during the provider release process?  

Specific issue is, given a `main.tf` of:
```tf
provider "checkly" {
  version = "~> 0.6"
  api_key = "xxx"
}

resource "checkly_check" "example-check" {
  name                      = "Example check"
  type                      = "API"
  activated                 = true
  should_fail               = false
  frequency                 = 1
  double_check              = true
  ssl_check                 = true
  use_global_alert_settings = true

  locations = [
    "us-west-1"
  ]

  request {
    url              = "https://api.example.com/"
    follow_redirects = true
    assertion {
      source     = "STATUS_CODE"
      comparison = "EQUALS"
      target     = "200"
    }
  }
}

```

Terraform validate returns:

```terraform
Warning: Interpolation-only expressions are deprecated

  on main.tf line 4, in provider "checkly":
   4:   api_key = "${var.checkly_api_key}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


Error: "request.0.basic_auth": required field is not set

  on main.tf line 7, in resource "checkly_check" "example-check":
   7: resource "checkly_check" "example-check" {
```

Versions are:
```shell
$ terraform version
Terraform v0.12.26
+ provider.checkly v0.6.0
```

**Comment by dijitali** [comment]
I don't think that's the same thing as this. #5 seems to be a terraform "permadiff" bug whereas what I'm seeing is that the `basic_auth` attribute has become mandatory since 99af175.

This issue can be reproduced with `terraform validate` on a fresh configuration and without any state being created, whereas yours seems to be a problem with state inconsistency.

Apologies, I think I have confused the issue by mentioning examples/tests.  I thought the `checkly_check` resource had changed without any corresponding documentation to explain it.  I think this is actually just a bug because otherwise if `basic_auth` is mandatory, it's impossible to use any other authentication scheme (digest, OAuth2 etc.).

**Comment by tnolet** [comment]
@dijitali thanks for reporting. We are moving to get the API out of beta and this provider to match up to that. We are making some breaking changes before we rip off the beta tag. We'll look into this issue ASAP.

**Comment by tnolet** [comment]
@kjda can you verify this behaviour and see:
- is it blocking, e.g. does prohibit using other auth providers (using setup scripts)
- can we provide an empty values as workaround, i.e.

```
 basic_auth {
      username = ""
      password = ""
    }
```
- what would a permanent fix be?

**Comment by kjda** [comment]
@tnolet i think any auth method should be optional. providing empty values is equivalent to making it optional. so i think making it optional should fix this issue, unless there's a good reason it was made required @bitfield ?

**Comment by bitfield** [comment]
Yes, `basic_auth` is now required by the API, so the Terraform provider requires it too. This is necessary to eliminate plan churn (if we don't send `basic_auth`, then the API sets the defaults and sends it back to us anyway, so the Terraform state is now different to the user's code, which creates plan churn).

**Comment by tnolet** [comment]
Just to track this as it is similar or the same as the issue tracked here https://github.com/checkly/terraform-provider-checkly/issues/5
