### ISSUE TITLE
unexpected response status on check group creation

### ISSUE THREAD

**Issue by ragog** [checkly/terraform-provider-checkly#15]
Using the latest (0.6.0) version of terraform-provider-checkly and the following terraform file:

```
resource "checkly_check_group" "ragog0" {
name = "ragog0"
activated = true
muted = false
tags = [
"ragog0"
]
concurrency = 3
locations = [
"eu-central-1",
"eu-west-1",
"eu-west-2",
"eu-west-3",
"eu-north-1",
]
}

```

I get the following error.

`Error: API error: unexpected response status 400: "{\"statusCode\":400,\"error\":\"Bad Request\",\"message\":\"child \\\"apiCheckDefaults\\\" fails because [child \\\"Headers\\\" fails because [\\\"Headers\\\" must be an array]]\",\"validation\":{\"source\":\"payload\",\"keys\":[\"apiCheckDefaults.headers\"]}}" on owner-bcd-e2e.tf line 1, in resource "checkly_check_group" "owner-bcd-e2e": 1: resource "checkly_check_group" "owner-bcd-e2e" {`

Am I missing a required parameter, or anything similar? Is there a way to update the docs to reflect it?

**Comment by tnolet** [comment]
@ragog @bitfield the answer is in the 400 error. the `apiCheckDefaults` object is required and should be a well formed object as per the API docs at https://www.checklyhq.com/docs/api#tocsmodel_2

My guess, just add:

```
api_check_defaults {
    url = ""
    headers = {}
    query_parameters = {}
    basic_auth {
      username = ""
      password = ""
    }
  }
```

**Comment by ragog** [comment]
@tnolet you beat me and @kjda to it by a few minutes. To your response I would add that the `assertions` child should also be set to an empty array by default. I am then able to create the group through the API - not tested through the provider yet though.

**Comment by tnolet** [comment]
@ragog @kjda cool! Seems mostly a docs / education issue. We are working on making that better

**Comment by kjda** [comment]
this issue is caused by standard go's encoding/json way of encoding empty nil slices, it just transform them into `null` instead of `[]` I'll be looking into this & will try to come up with a way to avoid this issue at all
