### ISSUE TITLE
State determines `ssl_check` is always false

### ISSUE THREAD

**Issue by RobertWTeamwork** [checkly/terraform-provider-checkly#162]
Hi there,

ssl_check has been set to true since the beginning yet the TF state determines it is set to false, therefore once a tf plan is run, it will show it setting ssl_check to true even though it is true in reality and in the TF document.

### Terraform Version
```

Terraform v1.1.8
on linux_amd64
+ provider registry.terraform.io/checkly/checkly v1.4.3
+ provider registry.terraform.io/hashicorp/aws v4.11.0

```

### Affected Resource(s)
Please list the resources as a list, for example:
- checkly_check

### Terraform Configuration Files
```

resource "checkly_check" "ssl_proxy" {
  group_id          = checkly_check_group.check_group.id
  activated         = true
  max_response_time = 20000
  frequency         = 5
  name              = "<REDACTED>"
  should_fail       = false
  ssl_check         = true

  type                      = "API"
  use_global_alert_settings = true

  request {
    body_type        = "NONE"
    follow_redirects = true
    headers          = {}
    method           = "GET"
    query_parameters = {}
    skip_ssl         = true
    url              = "<REDACTED>"
  }
}


```

### Debug Output
```

 # checkly_check.ssl_proxy will be updated in-place
  ~ resource "checkly_check" "ssl_proxy" {
        id                        = "<redacted id>"
        name                      = "<redacted name>"
      ~ ssl_check                 = false -> true
        tags                      = []



```

### Expected Behavior
ssl_check should be set as true, and therefore shouldn't show in the TF plan. 

### Actual Behavior
ssl_check had been always set to true yet every time we run the terraform plan, it has it set as false even though it never has been false.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform plan

**Comment by ianaya89** [comment]
Hi @RobertWTeamwork, thanks for reporting this.
We have removed the `sslCheck` property from our check schema. 
It was no longer used for a while and does not make sense to keep.
You can remove this property from all your checks.

**Comment by ianaya89** [comment]
@RobertWTeamwork will close this issue, feel free to open it again if needed
