### ISSUE TITLE
Alert channel management

### ISSUE THREAD

**Issue by tkowalcz** [checkly/terraform-provider-checkly#19]
I would like to be able to manage alert channels through Terraform configuration. Right now when creating a check it is only possible to specify `use_global_alert_settings` property.

**Comment by tnolet** [comment]
@tkowalcz thanks for mentioning this. This is on our list, but a little bit more tricky to achieve due the pub/sub type data model we use. We want to not expose our exact data model via the API, but do something easier/better. In general, we are working to pushing the public API to a GA status (not beta) and mapping all the resources in the API to the Terraform provider.

**Comment by tkowalcz** [comment]
For my use case what would be needed is just a resource alert channel and channel-check attachment. Like this:

```terraform
resource "checkly_check" "api-check" {
...
}


resource "checkly_alert_channel" "email" {
...
}

resource "checkly_alert_channel_check_attachment" "send-email" {
    check = checkly_check.api-check.id
    channel = checkly_alert_channel.email.id
}
```

or alternatively list of checks that given channel attaches to:

```terraform
resource "checkly_check" "api-check" {
...
}

resource "checkly_alert_channel" "email" {
attach_to = [checkly_check.api-check.id]
}
```

What goes inside `checkly_alert_channel` so channel resource is universally useful is another story

**Comment by drubin** [comment]
We also require this, as we manage all alerts via code too.

But I don't really understand this logic. I would much prefer to see something like this

```tf
resource "checkly_alert_channel" "email" {
...
}

resource "checkly_check" "api-check" {
   alert_settings {
      alert_channel {
          id = checkly_alert_channel.email.id
      }
    }
}
```

Something else I would LOVE to see as well is this 

```tf
resource "checkly_alert_channel" "slack" {
...
}

resource "checkly_check" "api-check" {
   alert_settings {
      alert_channel {
          id = checkly_alert_channel.slack.id
          channel = "#channel_override OR @user"
      }
    }
}
```

This would allow you to reuse the API token but have custom alerts going to custom  channels/users

**Comment by tnolet** [comment]
@drubin thanks for the input. We will use this when we start implementing these resources.

**Comment by drubin** [comment]
@tnolet if you can provide the raw API's we might be able to help with adding them to Terraform and submitting a PR

**Comment by tnolet** [comment]
@drubin that would be awesome, we however do not have the alert channels and their connection to checks on the public API yet. This will happen ASAP.

**Comment by tnolet** [comment]
We need to tackle this in two phases:

## Enable alert channel & subscription management in the public API

1. Extend the public schema with `groupId` (see https://www.checklyhq.com/docs/api#update-the-subscriptions-of-an-alert-channel)
2. Extend the public `check` and `check_group` schemas to include a list of subscribed alert channels. Currently, we allow subscribing by adding check ID's from the alert channel perspective. This is fine, but in Terraform it makes more sense to add alert channels to the check, .e.g. from the check perspective

One of the gotcha's here is that the `config` field of every alert channel is an unstructured JSON field. This is very useful for us in our internal data model, but less useful when exposed on the public API. This field hold different data items depending on the type of alert channel, e.g. email, webhook, pagerduty, opsgenie etc.

## Expose a "Terraform canonical" way to do CRUD and subscription for checks and check groups

The suggestions made by @drubin are useful, but I think we need to tweak them a little. We have roughly two options:

1. We hide the `subscription` data item and handle it implicitly. A user assigns an alert channel to check or check group using the alert channel ID and we turn this into a subscription.

2. We expose the concept of `subscriptions`.

In both cases, we would still need to give the user the specific subscription options like the `enabled` boolean. For this reason option two has my preference.

**Comment by umutuzgur** [comment]
Hey everyone, we have just rolled out the alert channels support with the terraform provider. You can find the documentation at https://github.com/checkly/terraform-provider-checkly/blob/master/docs/resources/alert-channel.md. 

Thanks a lot for the great suggestions! It really helped us shape the syntax
