### ISSUE TITLE
docs: Resource naming conventions to follow standard

### ISSUE THREAD

**Issue by Coolomina** [checkly/terraform-provider-checkly#190]
### What is the improvement or update you wish to see?

While the provider is still relatively small, I think it would be great to standardise naming conventions across resource names. 

Example of resource naming with no naming convention:

```terraform
resource "checkly_check" "browser-check-1" {}
resource "checkly_alert_channel" "email_ac" {}
```

Example of resource naming with a naming convention:

```terraform
resource "checkly_check" "browser_check_1" {}
resource "checkly_alert_channel" "email_ac" {}
```

You can find different resource name conventions in [alert_channel](https://github.com/checkly/terraform-provider-checkly/blob/v1.6.2/docs/resources/alert_channel.md?plain=1#L17) and in [environment variable](https://github.com/checkly/terraform-provider-checkly/blob/v1.6.2/docs/resources/environment_variable.md?plain=1#L17), among others.

### Is there any context that might help us understand?

A very well crafted guide on Terraform best practices is https://www.terraform-best-practices.com/naming, by Anton Babenko. I think it's relatively free to change the names in the examples.

**Comment by ianaya89** [comment]
@Coolomina thanks for your contribution. I think what you suggest will be a great addition. We will be executing this in the upcoming days.
