### ISSUE TITLE
bug: Both `time_based_escalation` and `run_based_escalation` are required, even through they're mutually exclusive

### ISSUE THREAD

**Issue by RealOrangeOne** [checkly/terraform-provider-checkly#194]
### Terraform version

1.2.9

### Provider version

1.6.2

### Steps to reproduce

Define a group with alert settings:

```hcl
  alert_settings {
    escalation_type = "RUN_BASED"

    run_based_escalation {
      failed_run_threshold = 1
    }

    ssl_certificates {
      alert_threshold = 3
      enabled         = false
    }

    reminders {
      amount   = 5
      interval = 15
    }
  }
```

### What is expected?

I only need to define one of `time_based_escalation` or `run_based_escalation`

### What is actually happening?

I need to define both `time_based_escalation` and `run_based_escalation`, and just ignore the values in the one I don't actually use as part of `escalation_type`.

This is similar to #193, but I think sufficiently different to warrant its own issue.

### Any additional comments?

I realise the current schema mirrors the REST API, but as this is being typed by hand, perhaps instead the `escalation_type` could be derived from which of the `*_based_escalation` blocks is defined, with some Terraform validation to only allow one.

**Comment by ianaya89** [comment]
Hey @RealOrangeOne, thanks for reporting this. You are absolutely right about this; the mistake currently resides in the Public API. I can quickly fix that, but I want to avoid breaking changes in current setups. I will work in a custom validation when handling both properties in the resources.
