### ISSUE TITLE
docs: remove guides from docs

### ISSUE THREAD

**Issue by pilimartinez** [checkly/terraform-provider-checkly#196]
### What is the improvement or update you wish to see?

Remove guides from docs to avoid repeated information

### Is there any context that might help us understand?

Avoid repeated information

Fixed #197

**Comment by ianaya89** [comment]
@pilimartinez which is the status of this?

**Comment by pilimartinez** [comment]
Fixed https://github.com/checkly/terraform-provider-checkly/pull/197
