### ISSUE TITLE
docs:  body and body_type not correctly defined

### ISSUE THREAD

**Issue by gespi-consensys** [checkly/terraform-provider-checkly#226]
### What is the improvement or update you wish to see?

the body and body type descriptions need to be flipped. Also body needs a description as well

### Is there any context that might help us understand?

every other parameter has a proper definition. Please add a proper definition for body and body_type.

### Does the docs page already exist? Please link to it.

https://github.com/checkly/terraform-provider-checkly/blob/e444769d5341af0e4f6575f12c78f98334713d4e/docs/resources/check.md?plain=1#L294

**Comment by ianaya89** [comment]
@gespi-consensys thanks for reporting, we will fix it soon!
