### ISSUE TITLE
 Warning: Argument is deprecated error

### ISSUE THREAD

**Issue by sachinmane1983** [checkly/terraform-provider-checkly#254]
### Story description

in terraform plan getting below warning
Warning: Argument is deprecated
│ 
│   with module.checkly.checkly_check_group.check-group,
│   on terraform-modules/checkly/checks.tf line 24, in resource "checkly_check_group" "check-group":
│   24:   environment_variables = each.value.environment_variables
│ 
│ The property `environment_variables` is deprecated and will be removed in a
│ future version. Consider using the new `environment_variable` list.
│ 
│ (and 26 more similar warnings elsewhere)

**Comment by pilimartinez** [comment]
Hello @sachinmane1983! As the warning says environment_variables property will be removed in a future version, but you should be able to use it. We still recommend migrating to new environment_variable property.

**Comment by sachinmane1983** [comment]
what is new approach for this?

**Comment by pilimartinez** [comment]
You can use it like this: 

  environment_variable {
    key    = "URL"
    value  = "https://mysite.com"
    locked = false
  }

Basically we made this change to give support to "locked" property.

**Comment by sachinmane1983** [comment]
prod-api = {
    name      = "PROD API"
    tags      = ["prod", "backend"]
    activated = true
    locations = [
      "eu-west-1",
      "eu-central-1",
      "eu-west-2",
      "eu-west-3",
      "eu-north-1",
    ]

    use_global_alert_settings = true

    api_check_defaults_url = "https://api.xxxx.co.xx/"

    environment_variables = []

    email_alert_channel_sub          = ""
    slack_alert_channel_sub          = ""
    pagerduty_alert_channel_sub      = ""
    opsgenie_alert_channel_sub       = ""
    grafana_oncall_alert_channel_sub = "grafana-oncall"
  },

variable "check_groups" {
  description = "Checkly groups to organise related checks"
  type = map(object({
    name                      = string
    tags                      = list(string)
    locations                 = list(string)
    use_global_alert_settings = bool

    api_check_defaults_url = string

    environment_variable = list(object({}))

    email_alert_channel_sub          = string
    slack_alert_channel_sub          = string
    pagerduty_alert_channel_sub      = string
    opsgenie_alert_channel_sub       = string
    grafana_oncall_alert_channel_sub = string
  }))

  default = {}
}

error
The given value is not suitable for var.check_groups declared at variables.tf:173,1-24: element "prod-api": attribute "environment_variable" is required.
