### ISSUE TITLE
Daddyzilla33@icloud.com

### ISSUE THREAD

**Issue by daddyzilla33** [checkly/terraform-provider-checkly#28]
**Describe the bug**

***Version***
What version of the Checkly Terraform provider are you using? e.g. v0.6.1

**To Reproduce**

**Expected behavior**

**TF Resource files**
If applicable, add TF resource file examples to help explain your problem.

**Additional context**

**Comment by daddyzilla33** [comment]
I need help with this

**Comment by tnolet** [comment]
@daddyzilla33 could you please describe your problem using the issue template?
