### ISSUE TITLE
Add resources for Snippets and Environment Variables

### ISSUE THREAD

**Issue by dijitali** [checkly/terraform-provider-checkly#3]
It'd be handy to be able to use this provider to setup the necessary snippets/environment variables we use in our checks.

**Comment by tnolet** [comment]
@dijitali this is going to happen. We are adding a dedicated developer to take care of this.

**Comment by kjda** [comment]
@dijitali we've added support for snippets. 
Environment variables will be added asap. I created a new ticket for environment variable & I'm closing this one
