### ISSUE TITLE
SSL checks are not added

### ISSUE THREAD

**Issue by vassbence** [checkly/terraform-provider-checkly#48]
**Describe the bug**
SSL cert checks are not uploaded correctly (at least they are not visible from the UI)
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/49574140/105099024-46488f80-5aab-11eb-8bb7-c254dc9c7ca7.png">

***Version***
v0.8.0

**To Reproduce**
Use this example check
```
resource "checkly_alert_channel" "email" {
  email {
    address = var.checkly_alert_email
  }
}

resource "checkly_check" "root_domain_check" {
  name                   = "root_domain_check"
  type                   = "API"
  activated              = true
  should_fail            = false
  frequency              = 30
  double_check           = true
  ssl_check              = true
  degraded_response_time = 300
  max_response_time      = 500

  locations = [
    "eu-central-1",
    "us-east-1"
  ]

  alert_settings {
    escalation_type = "RUN_BASED"

    run_based_escalation {
      failed_run_threshold = 2
    }

    ssl_certificates {
      enabled         = true
      alert_threshold = 30
    }

    reminders {
      amount   = 5
      interval = 30
    }
  }

  alert_channel_subscription {
    channel_id = checkly_alert_channel.email.id
    activated  = true
  }

  request {
    url              = "https://${local.website_domain}/"
    follow_redirects = false
    assertion {
      source     = "STATUS_CODE"
      comparison = "EQUALS"
      target     = "200"
    }
  }
}
```

**Expected behavior**
Should be able to set SSL cert checks via terraform

**Additional context**
Thanks for the awesome work, this is just a very minor thing I saw but I thought it was worth mentioning :)

**Comment by umutuzgur** [comment]
Hey @vassbence! Thanks for creating the issue. This apparently has slipped our attention. I will add it to our backlog to address it soon. We are really glad you enjoy using the terraform provider 🎉

**Comment by umutuzgur** [comment]
Hey @vassbence! You can now set the ssl settings in the new version. Thanks for lettings us know about it
