### ISSUE TITLE
docs: add documentation on how to add webhook based branded alert channels

### ISSUE THREAD

**Issue by umutuzgur** [checkly/terraform-provider-checkly#51]
**Describe the bug**
We don't document how to add webhook based alert channels, Microsoft Team and etc, in our documentation. We should have some example links on how they work and how to add them easily

**Comment by lukemelia** [comment]
Came here looking for how to do this for Discord

**Comment by ianaya89** [comment]
@ragog can you help with this?

**Comment by ragog** [comment]
@ianaya89 I will work on this as part of our current documentation initiative.
