### ISSUE TITLE
Add support for a Pagerduty alert channel

### ISSUE THREAD

**Issue by umutuzgur** [checkly/terraform-provider-checkly#53]
The pagerduty alert channel has to be created by the checkly UI at the moment. We should add support to it using the Terraform provider

**Comment by christopherbox** [comment]
Yes please!

I ran into this issue today with a Developer. Looks like we have to manually do the alert channel and then pass it off to the Developer. We don't have to do this on the PD side as they already have the necessary Terraform resource available.
