### ISSUE TITLE
Add support for a "get" request to grab all of the checks not in terraform

### ISSUE THREAD

**Issue by carly1uphealth** [checkly/terraform-provider-checkly#54]
Support some kind of "get" or "read" request to grab all of the checks not in terraform, so those checks can also be tracked in terraform. Our goal is to manage our checks only through code.

**Comment by tnolet** [comment]
@carly1uphealth great question! 

Short answer: no, Terraform does not really support that.

Long answer:

1a. Terraform does support this as their "discovery" feature. But only for a very limited set or resources. See https://registry.terraform.io/providers/hashicorp/oci/latest/docs/guides/resource_discovery#supported-resources

1b. Terraform has an `import` feature, but it does not really do what you intend. At least I assume. It still requires you to pinpoint the resource and only works for one resource at a time. See https://www.terraform.io/docs/cli/import/index.html

2. There are quite a bit of open source, 3rd party projects that kinda do this: they crawl some resource and then generate TF files from it. Example is: https://github.com/dtan4/terraforming

We don't have such a crawler and are not planning to build it right now.

Hope this helps

**Comment by carly1uphealth** [comment]
@tnolet got it! thank you!
