### ISSUE TITLE
Support for Apple Silicon (darwin/arm64)

### ISSUE THREAD

**Issue by cpressland** [checkly/terraform-provider-checkly#57]
**Describe the bug**
With the release of Go 1.16 we can now build for the darwin/arm64 architecture. Checkly should support this to allow developers on new hardware use the plugin without having to use the Rosetta 2 emulation layer.

**Comment by umutuzgur** [comment]
Hi @cpressland. Thanks for reporting this. We will address this swiftly

**Comment by umutuzgur** [comment]
Hi @cpressland, TF provider now has the darwin/arm64 binary starting with v1.0.0. Thanks for reporting this 🎉
