### ISSUE TITLE
target required on a checkly_check assertion comparasion type is IS_NULL

### ISSUE THREAD

**Issue by edgan** [checkly/terraform-provider-checkly#63]
**Describe the bug**
  I expect if I write a check with an assertion and the comparison type is IS_NULL that a target would not be required. If I create a check via the web ui, and it shows me the delta between the terraform code and the api results, it shows no target. If I specify a target with a value of "", it works. If I view that delta, it shows no target. So it half understands the target isn't required, but the provider still forces me to set a empty value.

***Version***
1.0.0

**To Reproduce**

    resource "checkly_check" "api_github" {
      name                      = "api_github"
      type                      = "API"
      activated                 = true
      should_fail               = false
      frequency                 = 1
      double_check              = true
      ssl_check                 = true
      use_global_alert_settings = true
      degraded_response_time    = 5000
      max_response_time         = 10000
 
      locations = var.locations
 
      request {
        url              = "https://github.com/"
        follow_redirects = true
        assertion {
          comparison = "IS_NULL"
          property   = "$.email"
          source     = "JSON_BODY"
        }
      }
    }

**Expected behavior**
target not required

**Error**

    terragrunt apply
    
    Error: Missing required argument
    
      on api_check.tf line 18, in resource "checkly_check" "api_github":
      18:     assertion {
    
    The argument "target" is required, but no definition was found.
    
    ERRO[0001] Hit multiple errors:
    Hit multiple errors:

**Additional context**

      ~ resource "checkly_check" "api_github" {
            id                        = "21829fe9-8b3c-4612-aa00-aea2e721b039"
            name                      = "api_github"
            tags                      = []
            # (16 unchanged attributes hidden)
 
 
          + request {
              + body_type        = "NONE"
              + follow_redirects = true
              + headers          = (known after apply)
              + method           = "GET"
              + query_parameters = (known after apply)
              + url              = "https://github.com/"
 
              + assertion {
                  + comparison = "IS_NULL"
                  + property   = "$.email"
                  + source     = "JSON_BODY"
                }
 
              + basic_auth {
                  + password = (known after apply)
                  + username = (known after apply)
                }
            }
          - request {
              - body_type        = "NONE" -> null
              - follow_redirects = true -> null
              - headers          = {} -> null
              - method           = "GET" -> null
              - query_parameters = {} -> null
              - url              = "https://github.com/" -> null
 
              - assertion {
                  - comparison = "IS_NULL" -> null
                  - property   = "$.signed_in" -> null
                  - source     = "JSON_BODY" -> null
                }
            }
            # (1 unchanged block hidden)
        }

**working code**

    resource "checkly_check" "api_github" {
      name                      = "api_github"
      type                      = "API"
      activated                 = true
      should_fail               = false
      frequency                 = 1
      double_check              = true
      ssl_check                 = true
      use_global_alert_settings = true
      degraded_response_time    = 5000
      max_response_time         = 10000
 
      locations = var.locations
 
      request {      
        url              = "https://github.com/"
        follow_redirects = true
        assertion {
          comparison = "IS_NULL"
          property   = "$.email"
          source     = "JSON_BODY"
          target     = ""
        }
      }
    }

**Comment by tnolet** [comment]
@edgan thanks for reporting! @umutuzgur @kjda let's have a look at this

**Comment by umutuzgur** [comment]
Added the P label. We will be tackling this soon. Thanks for reporting it @edgan
