### ISSUE TITLE
Support for Dashboards

### ISSUE THREAD

**Issue by dsalaza4** [checkly/terraform-provider-checkly#81]
Looking at the [provider documentation](https://registry.terraform.io/providers/checkly/checkly/latest/docs),
it seems like there is not a way for configuring dashboards. Are you planning to support this?

**Comment by ianaya89** [comment]
Hi @dsalaza4, thanks for reaching out!

Our Public API does not have support for Public Dashboard yet. We are working on expanding and improving our Public API right now but I can't say when we are going to have it.

Once the API work is done, we need to update our GO SDK and this provider.
I Will keep this issue open as a feature request and post updates here.

**Comment by tnolet** [comment]
@ianaya89 our API actually support public dashboards https://api.checklyhq.com/#/Dashboards

Adding it to the TF provider is not high on the roadmap right now. Maybe @pilimartinez can have a look?

**Comment by ianaya89** [comment]
@tnolet my bad. We still need to add it to GO SDK first. 
For sure @pilimartinez could take care of this, we will be able to start tackling this in the coming weeks.

**Comment by ianaya89** [comment]
Depends on https://github.com/checkly/checkly-go-sdk/issues/40

**Comment by ianaya89** [comment]
@dsalaza4 developed and released. Would be great to get your feedback later :)

**Comment by dsalaza4** [comment]
@ianaya89 I'll make sure to give it a shot next week. Thank you so much guys!

**Comment by dsalaza4** [comment]
Hi guys! 

I just tried the resource.

Everything LGTM except for one small detail in the documentation:

In the [example usage](https://registry.terraform.io/providers/checkly/checkly/latest/docs/resources/public_dashboards#example-usage), the `custom_domain` looks like this: `custom_domain   = "https://checklyhq.com/"`, which led me to keep the `https` portion and prevented the custom domain from loading (A 404 not found error was triggered).

This is how it looked via GUI: 
![image](https://user-images.githubusercontent.com/11205987/143077294-2942e7dd-939e-4500-9ee3-82c0aaf90a94.png)

I ended up fixing it with [this](https://gitlab.com/fluidattacks/product/-/merge_requests/17013/diffs).

This is how it looks now in the GUI:

![image](https://user-images.githubusercontent.com/11205987/143077760-34aa553b-ba54-45bd-9f90-83c1bf819ac9.png)


Maybe we should change the value given to `custom_domain` in the example to something without the `https://`.

Thank you so much once again guys!

**Comment by ianaya89** [comment]
@dsalaza4 thanks for your feedback, makes a lot of sense!

@pilimartinez could you take care of this? 🙏
